/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hygieniapeli;

import javax.swing.JTable;

/**
 *
 * @author Kukka
 */
public class JPanelResults extends javax.swing.JPanel {

    private GameController controller = null;
    /**
     * Creates new form JPanelResults
     */
    public JPanelResults() {
        initComponents();
    }

    public JTable getJTableResults() {
        return jTableResults;
    }
    
    public void setController (GameController pcontroller) {
        this.controller = pcontroller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelResults = new javax.swing.JPanel();
        jButtonResults = new javax.swing.JButton();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();

        jPanelResults.setBackground(new java.awt.Color(255, 0, 0));
        jPanelResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Korjaa!"));

        jButtonResults.setBackground(new java.awt.Color(204, 204, 204));
        jButtonResults.setForeground(new java.awt.Color(0, 102, 0));
        jButtonResults.setText("Tulokset");
        jButtonResults.setToolTipText("Klikkaamalla näet toimintojesi tulokset.");
        jButtonResults.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jButtonResults.setName("ResultButton"); // NOI18N
        jButtonResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultsActionPerformed(evt);
            }
        });

        jTableResults.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));
        jTableResults.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pilaantuu", null, null},
                {"Energiahukka", null, null},
                {"Haaskausta", null, null}
            },
            new String [] {
                "Virhe", "Lukumaara", "Kustannukset"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResults.setFillsViewportHeight(true);
        jTableResults.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableResults.getTableHeader().setReorderingAllowed(false);
        jScrollPaneResults.setViewportView(jTableResults);

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButtonResults, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonResults, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanelResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultsActionPerformed
        if (this.controller != null) this.controller.calculateResults();
    }//GEN-LAST:event_jButtonResultsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResults;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
