package hygieniapeli;

/**
 * This component has a food storage (PlainFoodStorage) with adjustable temperature.
 * 
 * @author Kukka
 */
public class JPanelCabinet extends javax.swing.JPanel {
    
    int tempValue; // "Model" for slider and textbox
    
    /**
     * Creates new form JPanelCabinet
     */
    public JPanelCabinet() {
        initComponents();
    } 

    public Integer getTempValue() {return this.tempValue;}
    public void setTempValues(int ptemp) { // MPC, controller does this since model is right here
        this.tempValue = ptemp;
        this.jFormattedTextFieldT.setValue(ptemp); // Slider is bound to the textfield, so it also changes
    }
    
    public javax.swing.JFormattedTextField getJFormattedTextFieldT() {
        return jFormattedTextFieldT;
    }
    public javax.swing.JSlider getJSliderT() {return jSliderT;}
    public PlainFoodStorage getPlainFoodStorage() {return this.plainFoodStorage;}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFormattedTextFieldT = new javax.swing.JFormattedTextField();
        jSliderT = new javax.swing.JSlider();
        cabinetLabel = new javax.swing.JLabel();
        cabinetLabelUnit = new javax.swing.JLabel();
        plainFoodStorage = new hygieniapeli.PlainFoodStorage();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Säilytystila"));
        setName("cabinetPanel"); // NOI18N

        jFormattedTextFieldT.setColumns(3);
        jFormattedTextFieldT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldT.setToolTipText("Lämpötilan voi syöttää myös tässä.");
        jFormattedTextFieldT.setName("cabinetTextField"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSliderT, org.jdesktop.beansbinding.ELProperty.create("${value}"), jFormattedTextFieldT, org.jdesktop.beansbinding.BeanProperty.create("value"), "bindTemp");
        bindingGroup.addBinding(binding);

        jSliderT.setForeground(new java.awt.Color(153, 153, 255));
        jSliderT.setMaximum(Food.highlimittemp);
        jSliderT.setMinimum(Food.lowlimittemp);
        jSliderT.setPaintLabels(true);
        jSliderT.setToolTipText("Säädä säilytystilan lämpötila.");
        jSliderT.setValue(20);
        jSliderT.setName("cabinetSlider"); // NOI18N

        cabinetLabel.setText("Temperature");

        cabinetLabelUnit.setText("C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cabinetLabel)
                .addGap(12, 12, 12)
                .addComponent(jFormattedTextFieldT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cabinetLabelUnit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jSliderT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(plainFoodStorage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cabinetLabel)
                    .addComponent(jFormattedTextFieldT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cabinetLabelUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSliderT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(plainFoodStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cabinetLabel;
    private javax.swing.JLabel cabinetLabelUnit;
    private javax.swing.JFormattedTextField jFormattedTextFieldT;
    private javax.swing.JSlider jSliderT;
    private hygieniapeli.PlainFoodStorage plainFoodStorage;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
