/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Components of the view.
 *
 * @author Kukka
 */
package hygieniapeli;
import javax.swing.JFormattedTextField;
public class MainGameFrame extends javax.swing.JFrame {

    final String FloorName="Lattia";
    final String RestaurantName="Restaurant";
    final String TrashName="Roskakori";
    final String WaitingName="Tarjolla";
    final String MouldName="Multa";
    final String ImportedName="Tuodut";
    
    final String ShelfString="Kaappi";
    final Integer DefaultTemp=20;

    ListTransferHandler lth;
    
    GameController MyController;
    
    /**
     * Creates new form MainGameFrame
     */
    public MainGameFrame() {
        lth = new ListTransferHandler(TrashName, WaitingName, MouldName, FloorName);
        initComponents();
        prepareList(jPanelRestaurant, lth);
        javax.swing.JOptionPane.showMessageDialog(null, "Tämä on kokeiluversio.  Faktat vielä väärin, pelaaminen omalla vastuulla.","Varoitus",javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    public void setGameController(GameController controller) {
        this.MyController = controller;
    }
    
    private void prepareList(java.awt.Component c, ListTransferHandler lth) {
        if (c != null && (c instanceof  java.awt.Container)) {
            if (c instanceof javax.swing.JList) {
                javax.swing.JList jc = (javax.swing.JList) c;
                jc.setTransferHandler(lth);
                jc.addMouseListener(new MouseDragHandler());
            }
            if (c instanceof javax.swing.JFormattedTextField) {
                javax.swing.JFormattedTextField tf = (javax.swing.JFormattedTextField) c;
                tf.addFocusListener(new java.awt.event.FocusListener() {
                    @Override
                    public void focusGained(java.awt.event.FocusEvent e) {}
                    @Override
                    public void focusLost(java.awt.event.FocusEvent e) {
                        try {
                            JFormattedTextField tf = (JFormattedTextField) e.getSource();
                            MyController.temperatures.put(tf.getName(), 
                            Integer.parseInt(tf.getText().trim()));
                        } catch (NumberFormatException ne) {}
                    }
                });
            }
            java.awt.Container jc = (java.awt.Container) c;
            for (java.awt.Component cc: jc.getComponents())
                prepareList(cc, lth);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRestaurant = new javax.swing.JPanel();
        jScrollPaneRoskis = new javax.swing.JScrollPane();
        jListRoskis = new javax.swing.JList();
        jScrollPaneMulta = new javax.swing.JScrollPane();
        jListMulta = new javax.swing.JList();
        jScrollPaneLattia = new javax.swing.JScrollPane();
        jListLattia = new javax.swing.JList();
        jPanelOhjaus = new javax.swing.JPanel();
        jButtonResults = new javax.swing.JButton();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jPanelSailytys = new javax.swing.JPanel();
        jPanelShelf1 = new javax.swing.JPanel();
        jScrollPaneKaappi1 = new javax.swing.JScrollPane();
        jListKaappi1 = new javax.swing.JList();
        jFormattedTextFieldShelf1T = new javax.swing.JFormattedTextField();
        jPanelShelf2 = new javax.swing.JPanel();
        jFormattedTextFieldShelf2T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi2 = new javax.swing.JScrollPane();
        jListKaappi2 = new javax.swing.JList();
        jPanelShelf3 = new javax.swing.JPanel();
        jFormattedTextFieldShelf3T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi3 = new javax.swing.JScrollPane();
        jListKaappi3 = new javax.swing.JList();
        jPanelShelf4 = new javax.swing.JPanel();
        jFormattedTextFieldShelf4T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi4 = new javax.swing.JScrollPane();
        jListKaappi4 = new javax.swing.JList();
        jPanelShelf5 = new javax.swing.JPanel();
        jFormattedTextFieldShelf5T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi5 = new javax.swing.JScrollPane();
        jListKaappi5 = new javax.swing.JList();
        jPanelShelf6 = new javax.swing.JPanel();
        jFormattedTextFieldShelf6T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi6 = new javax.swing.JScrollPane();
        jListKaappi6 = new javax.swing.JList();
        jPanelShelf7 = new javax.swing.JPanel();
        jFormattedTextFieldShelf7T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi7 = new javax.swing.JScrollPane();
        jListKaappi7 = new javax.swing.JList();
        jPanelShelf8 = new javax.swing.JPanel();
        jFormattedTextFieldShelf8T = new javax.swing.JFormattedTextField();
        jScrollPaneKaappi8 = new javax.swing.JScrollPane();
        jListKaappi8 = new javax.swing.JList();
        jScrollPaneTuodut = new javax.swing.JScrollPane();
        jListTuodut = new javax.swing.JList();
        jPanelTarjolla1 = new javax.swing.JPanel();
        jScrollPaneTarjolla1 = new javax.swing.JScrollPane();
        jListTarjolla1 = new javax.swing.JList();
        jFormattedTextFieldTarjolla1T = new javax.swing.JFormattedTextField();
        jPanelTarjolla2 = new javax.swing.JPanel();
        jScrollPaneTarjolla2 = new javax.swing.JScrollPane();
        jListTarjolla2 = new javax.swing.JList();
        jFormattedTextFieldTarjolla2T = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ravintola");

        jPanelRestaurant.setBackground(new java.awt.Color(153, 0, 153));
        jPanelRestaurant.setToolTipText("Ravintola");
        jPanelRestaurant.setName(this.RestaurantName);

        jListRoskis.setBackground(new java.awt.Color(255, 255, 0));
        jListRoskis.setBorder(javax.swing.BorderFactory.createTitledBorder("Roskakori"));
        jListRoskis.setModel(new FoodListModel());
        jListRoskis.setCellRenderer(new MyCellRenderer());
        jListRoskis.setDragEnabled(true);
        jListRoskis.setDropMode(javax.swing.DropMode.INSERT);
        jListRoskis.setName(this.TrashName);
        jScrollPaneRoskis.setViewportView(jListRoskis);

        jListMulta.setBackground(new java.awt.Color(102, 102, 102));
        jListMulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Multa"));
        jListMulta.setForeground(new java.awt.Color(255, 255, 255));
        jListMulta.setModel(new FoodListModel());
        jListMulta.setToolTipText("Kompostoi biojäte tänne");
        jListMulta.setCellRenderer(new MyCellRenderer());
        jListMulta.setDropMode(javax.swing.DropMode.INSERT);
        jListMulta.setName(this.MouldName);
        jScrollPaneMulta.setViewportView(jListMulta);

        jListLattia.setBackground(new java.awt.Color(51, 204, 0));
        jListLattia.setBorder(javax.swing.BorderFactory.createTitledBorder("Lattia"));
        jListLattia.setModel(new FoodListModel());
        jListLattia.setCellRenderer(new MyCellRenderer());
        jListLattia.setDragEnabled(true);
        jListLattia.setDropMode(javax.swing.DropMode.INSERT);
        jListLattia.setName(this.FloorName);
        jScrollPaneLattia.setViewportView(jListLattia);

        jPanelOhjaus.setBackground(new java.awt.Color(255, 0, 0));
        jPanelOhjaus.setBorder(javax.swing.BorderFactory.createTitledBorder("Korjaa!"));

        jButtonResults.setBackground(new java.awt.Color(0, 102, 0));
        jButtonResults.setForeground(new java.awt.Color(240, 240, 240));
        jButtonResults.setText("Tulokset");
        jButtonResults.setToolTipText("Klikkaamalla näet ravintolan tilanteen.");
        jButtonResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultsActionPerformed(evt);
            }
        });

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pilaantuu", null, null},
                {"Energiahukka", null, null},
                {"Haaskausta", null, null}
            },
            new String [] {
                "Virhe", "Lukumaara", "Kustannukset"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResults.getTableHeader().setReorderingAllowed(false);
        jScrollPaneResults.setViewportView(jTableResults);
        if (jTableResults.getColumnModel().getColumnCount() > 0) {
            jTableResults.getColumnModel().getColumn(0).setResizable(false);
            jTableResults.getColumnModel().getColumn(1).setResizable(false);
            jTableResults.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanelOhjausLayout = new javax.swing.GroupLayout(jPanelOhjaus);
        jPanelOhjaus.setLayout(jPanelOhjausLayout);
        jPanelOhjausLayout.setHorizontalGroup(
            jPanelOhjausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOhjausLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanelOhjausLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButtonResults)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOhjausLayout.setVerticalGroup(
            jPanelOhjausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOhjausLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonResults)
                .addContainerGap())
        );

        jPanelSailytys.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSailytys.setBorder(javax.swing.BorderFactory.createTitledBorder("Sailytys"));
        jPanelSailytys.setName("Sailytys"); // NOI18N
        jPanelSailytys.setLayout(new java.awt.GridLayout(2, 4, 10, 10));

        jListKaappi1.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi1.setBorder(javax.swing.BorderFactory.createTitledBorder(this.ShelfString));
        jListKaappi1.setModel(new FoodListModel());
        jListKaappi1.setToolTipText("Säädä yläpuolella olevasta napista lämpötila, ja varastoi ruoka tänne.");
        jListKaappi1.setCellRenderer(new MyCellRenderer());
        jListKaappi1.setDragEnabled(true);
        jListKaappi1.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi1.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi1.setName(this.ShelfString+"1");
        jListKaappi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi1MouseClicked(evt);
            }
        });
        jScrollPaneKaappi1.setViewportView(jListKaappi1);

        jFormattedTextFieldShelf1T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf1T.setColumns(3);
        jFormattedTextFieldShelf1T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf1T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf1T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf1T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf1T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf1T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf1T.setName("Kaappi1T"); // NOI18N
        jFormattedTextFieldShelf1T.setValue(DefaultTemp);
        jFormattedTextFieldShelf1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf1TActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShelf1Layout = new javax.swing.GroupLayout(jPanelShelf1);
        jPanelShelf1.setLayout(jPanelShelf1Layout);
        jPanelShelf1Layout.setHorizontalGroup(
            jPanelShelf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneKaappi1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldShelf1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanelShelf1Layout.setVerticalGroup(
            jPanelShelf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf1);

        jFormattedTextFieldShelf2T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf2T.setColumns(3);
        jFormattedTextFieldShelf2T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf2T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf2T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf2T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf2T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf2T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf2T.setName("Kaappi2T"); // NOI18N
        jFormattedTextFieldShelf2T.setValue(DefaultTemp);
        jFormattedTextFieldShelf2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf2TActionPerformed(evt);
            }
        });

        jListKaappi2.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi2.setModel(new FoodListModel());
        jListKaappi2.setCellRenderer(new MyCellRenderer());
        jListKaappi2.setDragEnabled(true);
        jListKaappi2.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi2.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi2.setName(this.ShelfString+"2");
        jListKaappi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi2MouseClicked(evt);
            }
        });
        jScrollPaneKaappi2.setViewportView(jListKaappi2);

        javax.swing.GroupLayout jPanelShelf2Layout = new javax.swing.GroupLayout(jPanelShelf2);
        jPanelShelf2.setLayout(jPanelShelf2Layout);
        jPanelShelf2Layout.setHorizontalGroup(
            jPanelShelf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf2Layout.setVerticalGroup(
            jPanelShelf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf2);

        jFormattedTextFieldShelf3T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf3T.setColumns(3);
        jFormattedTextFieldShelf3T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf3T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf3T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf3T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf3T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf3T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf3T.setName("Kaappi3T"); // NOI18N
        jFormattedTextFieldShelf3T.setValue(DefaultTemp);
        jFormattedTextFieldShelf3T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf3TActionPerformed(evt);
            }
        });

        jListKaappi3.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi3.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi3.setModel(new FoodListModel());
        jListKaappi3.setCellRenderer(new MyCellRenderer());
        jListKaappi3.setDragEnabled(true);
        jListKaappi3.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi3.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi3.setName(this.ShelfString+"3");
        jListKaappi3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi3MouseClicked(evt);
            }
        });
        jScrollPaneKaappi3.setViewportView(jListKaappi3);

        javax.swing.GroupLayout jPanelShelf3Layout = new javax.swing.GroupLayout(jPanelShelf3);
        jPanelShelf3.setLayout(jPanelShelf3Layout);
        jPanelShelf3Layout.setHorizontalGroup(
            jPanelShelf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf3T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf3Layout.setVerticalGroup(
            jPanelShelf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf3T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf3);

        jFormattedTextFieldShelf4T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf4T.setColumns(3);
        jFormattedTextFieldShelf4T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf4T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf4T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf4T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf4T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf4T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf4T.setName("Kaappi4T"); // NOI18N
        jFormattedTextFieldShelf4T.setValue(DefaultTemp);
        jFormattedTextFieldShelf4T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf4TActionPerformed(evt);
            }
        });

        jListKaappi4.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi4.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi4.setModel(new FoodListModel());
        jListKaappi4.setCellRenderer(new MyCellRenderer());
        jListKaappi4.setDragEnabled(true);
        jListKaappi4.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi4.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi4.setName(this.ShelfString+"4");
        jListKaappi4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi4MouseClicked(evt);
            }
        });
        jScrollPaneKaappi4.setViewportView(jListKaappi4);

        javax.swing.GroupLayout jPanelShelf4Layout = new javax.swing.GroupLayout(jPanelShelf4);
        jPanelShelf4.setLayout(jPanelShelf4Layout);
        jPanelShelf4Layout.setHorizontalGroup(
            jPanelShelf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf4T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf4Layout.setVerticalGroup(
            jPanelShelf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf4T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf4);

        jFormattedTextFieldShelf5T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf5T.setColumns(3);
        jFormattedTextFieldShelf5T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf5T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf5T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf5T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf5T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf5T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf5T.setName("Kaappi5T"); // NOI18N
        jFormattedTextFieldShelf5T.setValue(DefaultTemp);
        jFormattedTextFieldShelf5T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf5TActionPerformed(evt);
            }
        });

        jListKaappi5.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi5.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi5.setModel(new FoodListModel());
        jListKaappi5.setCellRenderer(new MyCellRenderer());
        jListKaappi5.setDragEnabled(true);
        jListKaappi5.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi5.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi5.setName(this.ShelfString+"5");
        jListKaappi5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi5MouseClicked(evt);
            }
        });
        jScrollPaneKaappi5.setViewportView(jListKaappi5);

        javax.swing.GroupLayout jPanelShelf5Layout = new javax.swing.GroupLayout(jPanelShelf5);
        jPanelShelf5.setLayout(jPanelShelf5Layout);
        jPanelShelf5Layout.setHorizontalGroup(
            jPanelShelf5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf5T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf5Layout.setVerticalGroup(
            jPanelShelf5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf5T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf5);

        jFormattedTextFieldShelf6T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf6T.setColumns(3);
        jFormattedTextFieldShelf6T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf6T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf6T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf6T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf6T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf6T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf6T.setName("Kaappi6T"); // NOI18N
        jFormattedTextFieldShelf6T.setValue(DefaultTemp);
        jFormattedTextFieldShelf6T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf6TActionPerformed(evt);
            }
        });

        jListKaappi6.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi6.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi6.setModel(new FoodListModel());
        jListKaappi6.setCellRenderer(new MyCellRenderer());
        jListKaappi6.setDragEnabled(true);
        jListKaappi6.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi6.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi6.setName(this.ShelfString+"6");
        jListKaappi6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi6MouseClicked(evt);
            }
        });
        jScrollPaneKaappi6.setViewportView(jListKaappi6);

        javax.swing.GroupLayout jPanelShelf6Layout = new javax.swing.GroupLayout(jPanelShelf6);
        jPanelShelf6.setLayout(jPanelShelf6Layout);
        jPanelShelf6Layout.setHorizontalGroup(
            jPanelShelf6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf6T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf6Layout.setVerticalGroup(
            jPanelShelf6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf6T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf6);

        jFormattedTextFieldShelf7T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf7T.setColumns(3);
        jFormattedTextFieldShelf7T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf7T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf7T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf7T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf7T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf7T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf7T.setName("Kaappi7T"); // NOI18N
        jFormattedTextFieldShelf7T.setValue(DefaultTemp);
        jFormattedTextFieldShelf7T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf7TActionPerformed(evt);
            }
        });

        jListKaappi7.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi7.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi7.setModel(new FoodListModel());
        jListKaappi7.setCellRenderer(new MyCellRenderer());
        jListKaappi7.setDragEnabled(true);
        jListKaappi7.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi7.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi7.setName(this.ShelfString+"7");
        jListKaappi7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi7MouseClicked(evt);
            }
        });
        jScrollPaneKaappi7.setViewportView(jListKaappi7);

        javax.swing.GroupLayout jPanelShelf7Layout = new javax.swing.GroupLayout(jPanelShelf7);
        jPanelShelf7.setLayout(jPanelShelf7Layout);
        jPanelShelf7Layout.setHorizontalGroup(
            jPanelShelf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf7T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf7Layout.setVerticalGroup(
            jPanelShelf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf7Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf7T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf7);

        jFormattedTextFieldShelf8T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldShelf8T.setColumns(3);
        jFormattedTextFieldShelf8T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf8T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldShelf8T.setToolTipText("Säädä kaapin lämpötila");
        jFormattedTextFieldShelf8T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldShelf8T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldShelf8T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldShelf8T.setName("Kaappi8T"); // NOI18N
        jFormattedTextFieldShelf8T.setValue(DefaultTemp);
        jFormattedTextFieldShelf8T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldShelf8TActionPerformed(evt);
            }
        });

        jListKaappi8.setBackground(new java.awt.Color(153, 255, 255));
        jListKaappi8.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaappi"));
        jListKaappi8.setModel(new FoodListModel());
        jListKaappi8.setCellRenderer(new MyCellRenderer());
        jListKaappi8.setDragEnabled(true);
        jListKaappi8.setDropMode(javax.swing.DropMode.INSERT);
        jListKaappi8.setMinimumSize(new java.awt.Dimension(10, 10));
        jListKaappi8.setName(this.ShelfString+"8");
        jListKaappi8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListKaappi8MouseClicked(evt);
            }
        });
        jScrollPaneKaappi8.setViewportView(jListKaappi8);

        javax.swing.GroupLayout jPanelShelf8Layout = new javax.swing.GroupLayout(jPanelShelf8);
        jPanelShelf8.setLayout(jPanelShelf8Layout);
        jPanelShelf8Layout.setHorizontalGroup(
            jPanelShelf8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShelf8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShelf8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldShelf8T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneKaappi8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelShelf8Layout.setVerticalGroup(
            jPanelShelf8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShelf8Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldShelf8T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneKaappi8, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSailytys.add(jPanelShelf8);

        jListTuodut.setBackground(new java.awt.Color(204, 102, 0));
        jListTuodut.setBorder(javax.swing.BorderFactory.createTitledBorder("Tuodut ruoat"));
        jListTuodut.setModel(new FoodListModel());
        jListTuodut.setToolTipText("Tilatut ruoat ovat tässä.  Laita ne heti asianmukaisiin lämpötiloihin.");
        jListTuodut.setCellRenderer(new MyCellRenderer());
        jListTuodut.setDragEnabled(true);
        jListTuodut.setName("Tuodut"); // NOI18N
        jScrollPaneTuodut.setViewportView(jListTuodut);

        jPanelTarjolla1.setPreferredSize(new java.awt.Dimension(256, 166));

        jListTarjolla1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjolla"));
        jListTarjolla1.setModel(new FoodListModel());
        jListTarjolla1.setToolTipText("Säädä yläpuolella olevasta boksista lämpötila, ja laita ruoka tänne tarjolle.");
        jListTarjolla1.setCellRenderer(new MyCellRenderer());
        jListTarjolla1.setDragEnabled(true);
        jListTarjolla1.setDropMode(javax.swing.DropMode.INSERT);
        jListTarjolla1.setName(this.WaitingName+"1");
        jListTarjolla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTarjolla1MouseClicked(evt);
            }
        });
        jScrollPaneTarjolla1.setViewportView(jListTarjolla1);

        jFormattedTextFieldTarjolla1T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldTarjolla1T.setColumns(3);
        jFormattedTextFieldTarjolla1T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldTarjolla1T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldTarjolla1T.setToolTipText("Säädä tarjolla olevien ruokien lämpötila");
        jFormattedTextFieldTarjolla1T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldTarjolla1T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldTarjolla1T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldTarjolla1T.setName("Tarjolla1T"); // NOI18N
        jFormattedTextFieldTarjolla1T.setValue(DefaultTemp);

        javax.swing.GroupLayout jPanelTarjolla1Layout = new javax.swing.GroupLayout(jPanelTarjolla1);
        jPanelTarjolla1.setLayout(jPanelTarjolla1Layout);
        jPanelTarjolla1Layout.setHorizontalGroup(
            jPanelTarjolla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarjolla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTarjolla1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarjolla1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldTarjolla1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanelTarjolla1Layout.setVerticalGroup(
            jPanelTarjolla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarjolla1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldTarjolla1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTarjolla1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jListTarjolla2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjolla"));
        jListTarjolla2.setModel(new FoodListModel());
        jListTarjolla2.setToolTipText("Säädä yläpuolella olevasta boksista lämpötila, ja laita ruoka tänne tarjolle.");
        jListTarjolla2.setCellRenderer(new MyCellRenderer());
        jListTarjolla2.setDragEnabled(true);
        jListTarjolla2.setDropMode(javax.swing.DropMode.INSERT);
        jListTarjolla2.setName(this.WaitingName+"2");
        jListTarjolla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTarjolla2MouseClicked(evt);
            }
        });
        jScrollPaneTarjolla2.setViewportView(jListTarjolla2);

        jFormattedTextFieldTarjolla2T.setBackground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldTarjolla2T.setColumns(3);
        jFormattedTextFieldTarjolla2T.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldTarjolla2T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldTarjolla2T.setToolTipText("Säädä tarjolla olevien ruokien lämpötila");
        jFormattedTextFieldTarjolla2T.setCaretColor(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldTarjolla2T.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldTarjolla2T.setInputVerifier(new TempVerifier(jFormattedTextFieldTarjolla2T, this.DefaultTemp));
        jFormattedTextFieldTarjolla2T.setName("Tarjolla2T"); // NOI18N
        jFormattedTextFieldTarjolla2T.setValue(DefaultTemp);
        jFormattedTextFieldTarjolla2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTarjolla2TActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarjolla2Layout = new javax.swing.GroupLayout(jPanelTarjolla2);
        jPanelTarjolla2.setLayout(jPanelTarjolla2Layout);
        jPanelTarjolla2Layout.setHorizontalGroup(
            jPanelTarjolla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarjolla2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTarjolla2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarjolla2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldTarjolla2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanelTarjolla2Layout.setVerticalGroup(
            jPanelTarjolla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarjolla2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldTarjolla2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTarjolla2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jFormattedTextFieldTarjolla2T.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanelRestaurantLayout = new javax.swing.GroupLayout(jPanelRestaurant);
        jPanelRestaurant.setLayout(jPanelRestaurantLayout);
        jPanelRestaurantLayout.setHorizontalGroup(
            jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRestaurantLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOhjaus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTuodut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPaneRoskis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTarjolla2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTarjolla1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneLattia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanelSailytys, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelRestaurantLayout.setVerticalGroup(
            jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRestaurantLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneLattia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelSailytys, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelRestaurantLayout.createSequentialGroup()
                            .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelOhjaus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelTarjolla1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(jPanelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelRestaurantLayout.createSequentialGroup()
                                    .addComponent(jScrollPaneTuodut, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPaneMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRestaurantLayout.createSequentialGroup()
                                    .addComponent(jPanelTarjolla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPaneRoskis, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanelRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultsActionPerformed
        this.MyController.calculateResults();
    }//GEN-LAST:event_jButtonResultsActionPerformed

    private void jListKaappi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi1MouseClicked

    }//GEN-LAST:event_jListKaappi1MouseClicked

    private void jListKaappi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi2MouseClicked

    }//GEN-LAST:event_jListKaappi2MouseClicked

    private void jListTarjolla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTarjolla2MouseClicked

    }//GEN-LAST:event_jListTarjolla2MouseClicked

    private void jFormattedTextFieldShelf2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf2TActionPerformed
        
    }//GEN-LAST:event_jFormattedTextFieldShelf2TActionPerformed

    private void jFormattedTextFieldShelf1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf1TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf1TActionPerformed

    private void jFormattedTextFieldShelf3TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf3TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf3TActionPerformed

    private void jListKaappi3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi3MouseClicked

    private void jFormattedTextFieldShelf4TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf4TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf4TActionPerformed

    private void jListKaappi4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi4MouseClicked

    private void jFormattedTextFieldShelf5TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf5TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf5TActionPerformed

    private void jListKaappi5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi5MouseClicked

    private void jFormattedTextFieldShelf6TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf6TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf6TActionPerformed

    private void jListKaappi6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi6MouseClicked

    private void jFormattedTextFieldShelf7TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf7TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf7TActionPerformed

    private void jListKaappi7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi7MouseClicked

    private void jFormattedTextFieldShelf8TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldShelf8TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldShelf8TActionPerformed

    private void jListKaappi8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListKaappi8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListKaappi8MouseClicked

    private void jListTarjolla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTarjolla1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListTarjolla1MouseClicked

    private void jFormattedTextFieldTarjolla2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTarjolla2TActionPerformed

    }//GEN-LAST:event_jFormattedTextFieldTarjolla2TActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGameFrame().setVisible(true);
            }
        });
    }
     
class MouseDragHandler extends java.awt.event.MouseAdapter {
    @Override
    public void mousePressed(java.awt.event.MouseEvent e) {
        java.awt.Component c = (java.awt.Component) e.getSource();
        javax.swing.JList lc;
        if ((lc=GameUtilities.castToJList(c))==null) return;
        if (lc.getDragEnabled()) {
            lth.initSourceVariable(lc);
            lth.exportAsDrag(lc, e, javax.swing.TransferHandler.MOVE);
        }
    }
}  

    public int getDefaultTemp() {return DefaultTemp;}
    public javax.swing.JList getJListMulta() {return jListMulta;}
    public javax.swing.JList getJListRoskis() {return jListRoskis;}
    public javax.swing.JList getJListTuodut() {return jListTuodut;}
    public javax.swing.JPanel getJPanelSailytys() {return jPanelSailytys;}
    public javax.swing.JFormattedTextField getJFormattedTextFieldTarjolla1T() {return jFormattedTextFieldTarjolla1T;}
    public javax.swing.JFormattedTextField getJFormattedTextFieldTarjolla2T() {return jFormattedTextFieldTarjolla2T;}
    public javax.swing.JTable getJTableResults() {return jTableResults;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResults;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf1T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf2T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf3T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf4T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf5T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf6T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf7T;
    private javax.swing.JFormattedTextField jFormattedTextFieldShelf8T;
    private javax.swing.JFormattedTextField jFormattedTextFieldTarjolla1T;
    private javax.swing.JFormattedTextField jFormattedTextFieldTarjolla2T;
    private javax.swing.JList jListKaappi1;
    private javax.swing.JList jListKaappi2;
    private javax.swing.JList jListKaappi3;
    private javax.swing.JList jListKaappi4;
    private javax.swing.JList jListKaappi5;
    private javax.swing.JList jListKaappi6;
    private javax.swing.JList jListKaappi7;
    private javax.swing.JList jListKaappi8;
    private javax.swing.JList jListLattia;
    private javax.swing.JList jListMulta;
    private javax.swing.JList jListRoskis;
    private javax.swing.JList jListTarjolla1;
    private javax.swing.JList jListTarjolla2;
    private javax.swing.JList jListTuodut;
    private javax.swing.JPanel jPanelOhjaus;
    private javax.swing.JPanel jPanelRestaurant;
    private javax.swing.JPanel jPanelSailytys;
    private javax.swing.JPanel jPanelShelf1;
    private javax.swing.JPanel jPanelShelf2;
    private javax.swing.JPanel jPanelShelf3;
    private javax.swing.JPanel jPanelShelf4;
    private javax.swing.JPanel jPanelShelf5;
    private javax.swing.JPanel jPanelShelf6;
    private javax.swing.JPanel jPanelShelf7;
    private javax.swing.JPanel jPanelShelf8;
    private javax.swing.JPanel jPanelTarjolla1;
    private javax.swing.JPanel jPanelTarjolla2;
    private javax.swing.JScrollPane jScrollPaneKaappi1;
    private javax.swing.JScrollPane jScrollPaneKaappi2;
    private javax.swing.JScrollPane jScrollPaneKaappi3;
    private javax.swing.JScrollPane jScrollPaneKaappi4;
    private javax.swing.JScrollPane jScrollPaneKaappi5;
    private javax.swing.JScrollPane jScrollPaneKaappi6;
    private javax.swing.JScrollPane jScrollPaneKaappi7;
    private javax.swing.JScrollPane jScrollPaneKaappi8;
    private javax.swing.JScrollPane jScrollPaneLattia;
    private javax.swing.JScrollPane jScrollPaneMulta;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JScrollPane jScrollPaneRoskis;
    private javax.swing.JScrollPane jScrollPaneTarjolla1;
    private javax.swing.JScrollPane jScrollPaneTarjolla2;
    private javax.swing.JScrollPane jScrollPaneTuodut;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
