package hygieniapeli;

/**
 *
 * @author Kukka
 */
public class PlainFoodStorage extends javax.swing.JPanel {

    /**
     * Creates new form PlainFoodStorage
     */
    public PlainFoodStorage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneFood = new javax.swing.JScrollPane();
        jListFood = new javax.swing.JList();

        jListFood.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruoan säilytyspaikka"));
        jListFood.setForeground(new java.awt.Color(153, 153, 255));
        jListFood.setModel(new FoodListModel());
        jListFood.setToolTipText("Ruoan säilytyspaikka");
        jListFood.setCellRenderer(new MyCellRenderer());
        jListFood.setDragEnabled(true);
        jListFood.setDropMode(javax.swing.DropMode.INSERT);
        jListFood.setName("FoodList"); // NOI18N
        jScrollPaneFood.setViewportView(jListFood);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneFood, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    javax.swing.JList getJListFood() {
        return jListFood;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListFood;
    private javax.swing.JScrollPane jScrollPaneFood;
    // End of variables declaration//GEN-END:variables
}
