package hygieniapeli;
import java.util.ArrayList;

/**
 *
 * @author Kukka
 */
public class RestaurantFrame extends RootForm {
    
    /**
     * Creates new form RestaurantFrame   
     * @param FoodTable The foods that are to be imported to the restaurant
     * @param pDefaultTemp Default temperature for the frame
     * @param pselling  Storage or selling, different temperature legistlation
     * @param pnumOfFood How many food elements to import to the game
    */
    public RestaurantFrame(ArrayList<Food> FoodTable, int pDefaultTemp, boolean pselling, int pnumOfFood) {
        super(FoodTable, pDefaultTemp, pselling);
        this.initComponents();
        super.setMyTopComponents(basePanel1);
        super.setMyController(new GameController(this, FoodTable, pnumOfFood));
    }

    public javax.swing.JPanel getJPanelSailytys() {return this.jPanelSailytys;}
    public javax.swing.JPanel getJPanelTarjoilu() {return this.jPanelTarjoilu;}  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTarjoilu = new javax.swing.JPanel();
        jPanelCabinetTarjoilu1 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetTarjoilu2 = new hygieniapeli.JPanelCabinet();
        jPanelSailytys = new javax.swing.JPanel();
        jPanelCabinetSailytys1 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys2 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys3 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys4 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys5 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys6 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys7 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys8 = new hygieniapeli.JPanelCabinet();
        jPanelCabinetSailytys9 = new hygieniapeli.JPanelCabinet();
        basePanel1 = new hygieniapeli.BasePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ravintola");
        setBackground(new java.awt.Color(102, 0, 102));

        jPanelTarjoilu.setBorder(javax.swing.BorderFactory.createTitledBorder(jPanelTarjoilu.getName()));
        jPanelTarjoilu.setToolTipText("Tarjoilutilat");
        jPanelTarjoilu.setName("Tarjoilu"); // NOI18N
        jPanelTarjoilu.setLayout(new java.awt.GridLayout(1, 0));

        jPanelCabinetTarjoilu1.setName("cabinetPanel1"); // NOI18N
        jPanelTarjoilu.add(jPanelCabinetTarjoilu1);

        jPanelCabinetTarjoilu2.setName("cabinetPanel2"); // NOI18N
        jPanelTarjoilu.add(jPanelCabinetTarjoilu2);

        jPanelSailytys.setBorder(javax.swing.BorderFactory.createTitledBorder(jPanelSailytys.getName()));
        jPanelSailytys.setToolTipText("Säilytystilat");
        jPanelSailytys.setName("Säilytys"); // NOI18N
        jPanelSailytys.setLayout(new java.awt.GridLayout(3, 0));

        jPanelCabinetSailytys1.setName("cabinetPanel1"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys1);

        jPanelCabinetSailytys2.setName("cabinetPanel2"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys2);

        jPanelCabinetSailytys3.setName("cabinetPanel3"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys3);

        jPanelCabinetSailytys4.setName("cabinetPanel4"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys4);

        jPanelCabinetSailytys5.setName("cabinetPanel5"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys5);

        jPanelCabinetSailytys6.setName("cabinetPanel6"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys6);

        jPanelCabinetSailytys7.setName("cabinetPanel7"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys7);

        jPanelCabinetSailytys8.setName("cabinetPanel8"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys8);

        jPanelCabinetSailytys9.setName("cabinetPanel9"); // NOI18N
        jPanelSailytys.add(jPanelCabinetSailytys9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanelTarjoilu, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(basePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanelSailytys, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(basePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanelTarjoilu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelSailytys, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
 //               new RestaurantFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hygieniapeli.BasePanel basePanel1;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys1;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys2;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys3;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys4;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys5;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys6;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys7;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys8;
    private hygieniapeli.JPanelCabinet jPanelCabinetSailytys9;
    private hygieniapeli.JPanelCabinet jPanelCabinetTarjoilu1;
    private hygieniapeli.JPanelCabinet jPanelCabinetTarjoilu2;
    private javax.swing.JPanel jPanelSailytys;
    private javax.swing.JPanel jPanelTarjoilu;
    // End of variables declaration//GEN-END:variables
}
