/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hygieniapeli;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Kukka
 */
public abstract class RootForm extends javax.swing.JFrame {

    final boolean selling; // Selling or production (e.g. they use different temperatures)
    final Integer DefaultTemp;
    GameController MyController;
    BasePanel MyBasePanel;
    HashMap <String, javax.swing.JPanel> MyCabinetPanels = new HashMap();
    
    /**
     * Creates new form RootForm
     *
     * @param FoodTable     Food table for this form
     * @param pdefaultTemp  Default temperature for this form
     * @param pselling      Tells if this is a storage or selling place, different legistlation about temperatures
     */
    public RootForm(ArrayList<Food> FoodTable, int pdefaultTemp, boolean pselling) {
        selling = pselling;
        DefaultTemp = pdefaultTemp;
    }
    
    public Integer getDefaultTemp() {return DefaultTemp;}    
    public boolean isSelling() {return selling;}
    public BasePanel getBasePanel1() {return MyBasePanel;}

    /**
     * Attaches a base panel to the root form, and builds a hashmap about cabinet collections.
     * This also gives background color to content pane, base panel, and cabinet collections,
     * and a titled border to each cabinet collection.  This is called in a subframe when the
     * components of the subframe have been initialized.
     *
     * @param pBasePanel     Food table for this form
     */
    protected void setMyTopComponents(BasePanel pBasePanel) {
        MyBasePanel = pBasePanel;
        java.awt.Color mybgColor = new java.awt.Color(102,0,102);
        this.getContentPane().setBackground(mybgColor);
        MyBasePanel.setBackground(mybgColor);
        for (java.awt.Component cc: this.getContentPane().getComponents())
            if (cc != null && (cc instanceof javax.swing.JPanel)
            && !(cc.getName().equals(MyBasePanel.getName()))) {
                MyCabinetPanels.put(cc.getName(),(javax.swing.JPanel) cc);
                javax.swing.border.TitledBorder b = javax.swing.BorderFactory.createTitledBorder(cc.getName());
                b.setTitleColor(Color.white);
                ((javax.swing.JPanel) cc).setBorder(b);
                cc.setBackground(mybgColor);     
            }
    }
    
    public GameController getMyController() {
        return MyController;
    }
    
    protected void setMyController(GameController pcontroller) {
        MyController=pcontroller;
        this.MyBasePanel.setGameController(pcontroller);
    }

    public HashMap <String, javax.swing.JPanel> getMyCabinetPanels() {
        return MyCabinetPanels;
    }
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RootForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RootForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RootForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RootForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new RootForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
